# Register Endpoint EX
POST localhost:8080/users/register
Content-Type: application/json

{
    "name":"mobin-alz",
    "phone_number":"09902486977",
    "password":"12345678"
}


###
# Login Endpoint Ex
POST localhost:8080/users/login
Content-Type: application/json

{
    "phone_number":"09015037617",
    "password":"12345678"
}


###
# Get User Profile Endpoint
GET localhost:8080/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYyIsImV4cCI6MTc3NTUxMTI1OSwidXNlcl9pZCI6NH0.lpJgQTJDfrUXTqv7LJcvG6OEg9crJIFrIWpJrMQK-ms


###
